typedef struct lista lst;
typedef struct pilhaop po;
typedef struct pilhareais pf;
typedef struct calculadora ca;
po *criapo();
void popush(po *p,char c);
void poimp(po *p);
char popop(po *p);
void polibera(po *p);
pf *pfcria();
void pfpush(pf *p,float v);
float pfpop(pf *p);
void pfimp(pf *p);
void pflibera(pf *p);
ca *cacria();
void caopush(ca *c,char a);
void cafpush(ca *c,float v);
void caimp(ca *c);
int tamanho(pf *f);
int vazia(po *p);
void calculadora(ca *c);
void pcpush(pf *f,ca *c);
int cteste(ca *c);
